/* Traffic LOS quality and delivery extension v2.5.
   This module does not change the representative-record or LOS formulas. */
(function(){
'use strict';
const q=id=>document.getElementById(id);
const clone=x=>structuredClone(x);
const periodKey=v=>{const m=String(v||'').match(/^(\d{2,3})Q([1-4])$/);return m?Number(m[1])*4+Number(m[2]):-1};
const ordered=a=>[...new Set(a)].sort((x,y)=>periodKey(x)-periodKey(y));
const safe=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const csvCell=v=>`"${String(v??'').replaceAll('"','""')}"`;
const downloadBlob=(blob,name)=>{const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1500)};
const activeRows=()=>state.details.filter(x=>x.projectCode===state.activeCode);
const activeSummaries=()=>state.summaries.filter(x=>x.projectCode===state.activeCode);
const currentPeriod=()=>`${q('rocYear')?.value||''}Q${q('quarter')?.value||''}`;

function ensureState(){
 state.speedVersions=state.speedVersions||{};
 state.anomalyRules=state.anomalyRules||{};
 state.operations=state.operations||[];
 state.reportDrafts=state.reportDrafts||{};
 state.version=Math.max(Number(state.version)||0,10);
}
ensureState();
document.querySelector('.brand small').textContent='最終版 v2.5';

function injectUI(){
 const importPanel=document.createElement('article');
 importPanel.className='panel extension-panel';importPanel.id='quarterDiffPanel';
 importPanel.innerHTML='<div class="panel-head"><div><h3>與前一季差異檢查</h3><small>僅供寫入前核對，不改動資料</small></div><span class="status-neutral" id="diffStatus">尚未預覽</span></div><div id="diffContent" class="empty">完成辨識預覽後顯示</div><div id="representativePreview"></div>';
 q('roadAlert').after(importPanel);

 const sourcePanel=document.createElement('article');sourcePanel.className='panel extension-panel';
 sourcePanel.innerHTML='<div class="panel-head"><div><h3>來源追溯</h3><small>搜尋尖峰明細並查看原始檔、工作表、標籤位置與批次</small></div><input id="traceSearch" placeholder="搜尋路段、季度或檔名"></div><div class="table-wrap"><table><thead><tr><th>期間／路段</th><th>代表資料</th><th>來源檔案</th><th>工作表</th><th>標籤位置</th><th>批次／驗證碼</th></tr></thead><tbody id="traceRows"></tbody></table></div>';
 q('summary').append(sourcePanel);

 const versionPanel=document.createElement('article');versionPanel.className='panel extension-panel';versionPanel.id='speedVersionPanel';
 versionPanel.innerHTML='<div class="panel-head"><div><h3>速限有效期間與查證紀錄</h3><small>不同季度可套用不同速限；未設定版本時維持原本路段速限</small></div></div><div class="version-grid"><label>路段方向<select id="versionLimitKey"></select></label><label>公告速限（km/h）<input id="versionSpeed" type="number" min="1" value="50"></label><label>開始季度<input id="versionStart" placeholder="例如 114Q1"></label><label>結束季度<input id="versionEnd" placeholder="持續有效可留白"></label><label>資料來源<input id="versionSource" placeholder="例如：現場速限牌／機關公告"></label><label>查證日期<input id="versionChecked" type="date"></label><label>查證人員<input id="versionBy" placeholder="姓名"></label><label>備註<input id="versionNote" placeholder="選填"></label></div><button class="primary" id="saveSpeedVersion">新增速限版本並重算</button><div class="table-wrap"><table><thead><tr><th>路段／方向</th><th>速限</th><th>有效期間</th><th>來源</th><th>查證</th><th>操作</th></tr></thead><tbody id="speedVersionRows"></tbody></table></div>';
 q('speed').append(versionPanel);

 const quality=document.querySelector('.quality-panel');
 if(quality){
  const rules=document.createElement('article');rules.className='panel extension-panel';
  rules.innerHTML='<div class="panel-head"><div><h3>異常提醒門檻</h3><small>只影響提醒，不改變 LOS 計算</small></div><button class="primary" id="saveAnomalyRules">儲存門檻並重檢</button></div><div class="four"><label>旅行速率下降（%）<input id="ruleSpeedDrop" type="number" min="1" max="100"></label><label>總延滯增加（%）<input id="ruleDelayRise" type="number" min="1" max="100"></label><label>LOS 下降級數<input id="ruleLosDrop" type="number" min="1" max="5"></label><label>連續惡化季度<input id="ruleStreak" type="number" min="2" max="12"></label></div>';
  quality.before(rules);
 }
 const priority=document.createElement('article');priority.className='panel extension-panel';priority.id='priorityPanel';
 priority.innerHTML='<div class="panel-head"><div><h3>重點路段總覽</h3><small>依目前計畫自動排列需優先檢視的路段</small></div><button class="outline" id="refreshPriority">重新分析</button></div><div class="table-wrap"><table><thead><tr><th>優先度</th><th>路段／日別</th><th>最近期間</th><th>變化原因</th><th>建議</th></tr></thead><tbody id="priorityRows"></tbody></table></div>';
 q('maintenance').append(priority);

 const deliveryButton=document.createElement('button');deliveryButton.dataset.view='delivery';deliveryButton.textContent='成果交付';document.querySelector('nav button[data-view="maintenance"]').after(deliveryButton);deliveryButton.onclick=()=>go('delivery');titles.delivery='成果交付';
 const delivery=document.createElement('section');delivery.id='delivery';delivery.className='view';
 delivery.innerHTML='<div class="title"><div><span class="eyebrow">DELIVERY CENTER</span><h2>季度成果交付</h2><p>選擇季度與範圍，下載可追溯、可編輯的成果資料包。</p></div></div><div class="two"><article class="panel form"><h3>成果範圍</h3><label>季度<select id="deliveryPeriod"></select></label><label>路段<select id="deliveryRoad"><option value="">全部路段</option></select></label><label>日別<select id="deliveryDay"><option value="">平日與假日</option><option>平日</option><option>假日</option></select></label><label>Excel 圖表內容<select id="deliveryMetric"><option value="travel">旅行速率（km/h）</option><option value="los">服務水準（A～F）</option></select></label><div class="check-grid"><label><input type="checkbox" id="packDetail" checked>尖峰明細</label><label><input type="checkbox" id="packSummary" checked>尖峰彙總</label><label><input type="checkbox" id="packQuality" checked>品質檢查</label><label><input type="checkbox" id="packNarrative" checked>分析文字草稿</label></div><button class="primary full" id="downloadQuarterPack">下載季度成果包 ZIP</button><button class="outline full" id="downloadFilteredCharts">匯出篩選後可編輯 Excel 圖表</button></article><article class="panel form"><h3>報告文字草稿</h3><p class="muted">由現有彙總自動產生，必須由使用者確認後再放入正式報告。</p><textarea id="reportDraft" rows="18"></textarea><div class="row"><button class="outline" id="generateDraft">重新產生</button><button class="primary" id="saveDraft">儲存修改</button></div></article></div>';
 q('backup').before(delivery);

 const undo=document.createElement('article');undo.className='panel extension-panel';undo.id='undoPanel';
 undo.innerHTML='<div class="panel-head"><div><h3>最近操作與復原</h3><small>保留最近10次會改變分析結果的操作；匯入批次仍請優先由「匯入紀錄」復原</small></div></div><div class="table-wrap"><table><thead><tr><th>時間</th><th>操作</th><th>計畫</th><th>操作</th></tr></thead><tbody id="operationRows"></tbody></table></div>';
 q('backup').append(undo);
 const guide=document.createElement('article');guide.className='panel extension-panel';guide.innerHTML='<h3>十一、資料品質與成果交付（v2.5）</h3><ol><li><b>匯入前：</b>在辨識預覽下方檢查與前一季的路段、平假日及4筆資料差異，再核對預計代表紀錄。</li><li><b>來源追溯：</b>到「尖峰彙總」下方搜尋原始檔名、工作表、標籤位置、批次及檔案驗證碼。</li><li><b>速限變更：</b>到「路段速限」新增有效期間、資料來源、查證日期與人員；系統只重算有效季度。</li><li><b>異常分析：</b>到「資料維護」設定提醒門檻並查看重點路段；提醒不會改變服務水準。</li><li><b>成果交付：</b>到「成果交付」選擇季度、路段及日別，下載 ZIP 或可編輯 Excel 圖表。自動文字僅為草稿，正式使用前必須人工核對。</li><li><b>操作復原：</b>到「備份與淨空」查看最近操作；匯入錯誤仍優先從「匯入紀錄」復原。</li></ol>';
 document.querySelector('#guide .warning').before(guide);
}
injectUI();

function findSheetName(wb,targets){const ns=targets.map(normalize);for(const t of ns){const exact=wb.SheetNames.find(n=>normalize(n)===t);if(exact)return exact;const near=wb.SheetNames.find(n=>normalize(n).includes(t));if(near)return near}return''}
function refsForSheet(wb,name){if(!name)return[];const m=XLSX.utils.sheet_to_json(wb.Sheets[name],{header:1,raw:true,defval:null}),labels=['平均總旅行速率','平均總行駛速率','路段延滯','交叉口延滯'],refs=[];for(const label of labels)for(const p of findLabels(m,label))refs.push(`${label}:${XLSX.utils.encode_cell({r:p.r,c:p.c})}`);return refs}
async function digestFile(file){try{const b=await crypto.subtle.digest('SHA-256',await file.arrayBuffer());return[...new Uint8Array(b)].map(x=>x.toString(16).padStart(2,'0')).join('').slice(0,16)}catch{return''}}
const baseParseFile=parseFile;
parseFile=async function(file,year,quarter,defSpeed){
 const result=await baseParseFile(file,year,quarter,defSpeed);
 try{
  const wb=XLSX.read(await file.arrayBuffer(),{type:'array',cellFormula:false}),am=findSheetName(wb,['上午尖峰','上午','AM尖峰','AM']),pm=findSheetName(wb,['下午尖峰','下午','PM尖峰','PM']),hash=await digestFile(file),maps={上午尖峰:{sheet:am,refs:refsForSheet(wb,am)},下午尖峰:{sheet:pm,refs:refsForSheet(wb,pm)}};
  result.rows.forEach(r=>Object.assign(r,{sourceFile:file.name,sourceSheet:maps[r.peak]?.sheet||'',sourceRefs:maps[r.peak]?.refs||[],sourceHash:hash}));
 }catch{}
 return result;
};

function priorPeriod(period){const all=ordered(activeRows().map(x=>x.period).concat(period)).filter(x=>periodKey(x)<periodKey(period));return all.at(-1)||''}
function previewDifferences(){
 if(!pending.length){q('diffStatus').textContent='尚未預覽';q('diffContent').innerHTML='<div class="empty">完成辨識預覽後顯示</div>';q('representativePreview').innerHTML='';return}
 const period=currentPeriod(),prev=priorPeriod(period),good=pending.filter(x=>x.ok),newRoads=[...new Set(good.filter(x=>x.matchType==='新路段').map(x=>x.road))],incoming=new Set(good.map(x=>x.roadChoice&&x.roadChoice!=='__NEW__'?x.roadChoice:x.road)),previous=prev?new Set(activeRows().filter(x=>x.period===prev).map(x=>x.road)):new Set(),missing=[...previous].filter(x=>!incoming.has(x)),groups=good.filter(x=>x.rows.length!==4),dayMap={};good.forEach(x=>(dayMap[x.road]??=new Set()).add(x.day));const missingDays=Object.entries(dayMap).filter(([,v])=>!v.has('平日')||!v.has('假日')).map(([k,v])=>`${k}（${[...v].join('、')||'無'}）`);
 const warnings=newRoads.length+missing.length+groups.length+missingDays.length;q('diffStatus').textContent=warnings?`${warnings} 類需確認`:'未發現結構差異';q('diffStatus').className=warnings?'status-warn':'status-ok';
 q('diffContent').innerHTML=`<div class="diff-grid"><div><b>比較基準</b><span>${prev||'沒有前一季資料'}</span></div><div><b>新路段</b><span>${newRoads.length?newRoads.map(safe).join('、'):'無'}</span></div><div><b>前季有、本季未出現</b><span>${missing.length?missing.map(safe).join('、'):'無'}</span></div><div><b>平假日不成對</b><span>${missingDays.length?missingDays.map(safe).join('、'):'無'}</span></div><div><b>非4筆資料檔</b><span>${groups.length?groups.map(x=>safe(x.file)).join('、'):'無'}</span></div></div>`;
 const candidates=good.map(item=>{const rows=[...item.rows].sort((a,b)=>(losRank[a.los]||9)-(losRank[b.los]||9)||(a.ratio??9)-(b.ratio??9)||(a.travel??999)-(b.travel??999)),w=rows[0];return w?`<tr><td>${safe(item.road)}</td><td>${safe(item.day)}</td><td>${safe(w.peak)}</td><td>${safe(directionName(item.road,w.direction,w.projectCode))}</td><td>${fmt(w.travel,2)}</td><td>${fmt(w.running,2)}</td><td>${fmt(w.totalDelay,2)}</td><td>${losChip(w.los)}</td><td>${safe(w.sourceSheet||'—')}</td></tr>`:''}).join('');
 q('representativePreview').innerHTML=`<h4>預計代表紀錄（尚未寫入）</h4><div class="table-wrap"><table><thead><tr><th>路段</th><th>日別</th><th>代表尖峰</th><th>方向</th><th>旅行速率</th><th>行駛速率</th><th>總延滯</th><th>LOS</th><th>來源工作表</th></tr></thead><tbody>${candidates}</tbody></table></div>`;
}
const baseRenderPreview=renderPreview;renderPreview=function(){baseRenderPreview();previewDifferences()};

function speedFor(row){const key=`${row.projectCode}|${row.road}|${row.direction}`,versions=state.speedVersions[key]||[],hit=versions.filter(v=>periodKey(row.period)>=periodKey(v.start)&&(!v.end||periodKey(row.period)<=periodKey(v.end))).sort((a,b)=>periodKey(b.start)-periodKey(a.start))[0];return hit||null}
const baseRebuild=rebuild;rebuild=function(){ensureState();for(const d of state.details){const version=speedFor(d);if(version){d.limit=Number(version.speed);d.limitSource=version.source||'';d.limitVersionStart=version.start;d.ratio=d.travel/d.limit}}baseRebuild()};

function renderTrace(){if(!q('traceRows'))return;const term=normalize(q('traceSearch').value||''),rows=activeRows().filter(x=>!term||normalize([x.period,x.road,x.sourceFile,x.sourceSheet].join(' ')).includes(term));q('traceRows').innerHTML=rows.length?rows.slice(0,500).map(x=>`<tr><td>${safe(x.period)}<br>${safe(x.road)}／${safe(x.day)}</td><td>${safe(x.peak)}／${safe(directionName(x.road,x.direction,x.projectCode))}</td><td>${safe(x.sourceFile||x.source||'舊資料未記錄')}</td><td>${safe(x.sourceSheet||'舊資料未記錄')}</td><td>${safe((x.sourceRefs||[]).join('、')||'舊資料未記錄')}</td><td>${safe(x.importBatch||'—')}<br><small>${safe(x.sourceHash||'—')}</small></td></tr>`).join(''):'<tr><td colspan="6" class="empty">沒有符合的來源紀錄</td></tr>'}
q('traceSearch').oninput=renderTrace;

function speedKeys(){return[...new Set(activeRows().map(x=>`${x.projectCode}|${x.road}|${x.direction}`))].sort()}
function renderSpeedVersions(){if(!q('versionLimitKey'))return;const keys=speedKeys(),old=q('versionLimitKey').value;q('versionLimitKey').innerHTML=keys.map(k=>{const p=k.split('|'),dir=p.pop(),road=p.pop();return`<option value="${safe(k)}">${safe(road)}／${safe(directionName(road,dir,state.activeCode))}</option>`}).join('')||'<option value="">尚無路段</option>';if(keys.includes(old))q('versionLimitKey').value=old;const all=keys.flatMap(k=>(state.speedVersions[k]||[]).map(v=>({k,...v}))).sort((a,b)=>periodKey(b.start)-periodKey(a.start));q('speedVersionRows').innerHTML=all.length?all.map((v,i)=>{const p=v.k.split('|'),dir=p.pop(),road=p.pop();return`<tr><td>${safe(road)}／${safe(directionName(road,dir,state.activeCode))}</td><td>${v.speed} km/h</td><td>${safe(v.start)}～${safe(v.end||'持續')}</td><td>${safe(v.source||'—')}</td><td>${safe(v.checked||'—')}／${safe(v.by||'—')}</td><td><button class="outline" data-remove-version="${safe(v.k)}" data-version-id="${safe(v.id)}">刪除</button></td></tr>`}).join(''):'<tr><td colspan="6" class="empty">尚未設定期間版本，沿用上方路段速限</td></tr>';document.querySelectorAll('[data-remove-version]').forEach(b=>b.onclick=async()=>{recordOperation('刪除速限版本');state.speedVersions[b.dataset.removeVersion]=(state.speedVersions[b.dataset.removeVersion]||[]).filter(v=>v.id!==b.dataset.versionId);rebuild();await save();toast('速限版本已刪除並重算')})}
q('saveSpeedVersion').onclick=async()=>{const key=q('versionLimitKey').value,start=q('versionStart').value.trim().toUpperCase(),end=q('versionEnd').value.trim().toUpperCase(),speed=Number(q('versionSpeed').value);if(!key||!validPeriod(start)||!start||!validPeriod(end)||!speed)return toast('請輸入路段、有效速限及正確季度');if(end&&periodKey(start)>periodKey(end))return toast('結束季度不可早於開始季度');const existing=state.speedVersions[key]||[],overlap=existing.some(v=>periodKey(start)<=periodKey(v.end||'999Q4')&&periodKey(v.start)<=periodKey(end||'999Q4'));if(overlap&&!confirm('此期間與既有速限版本重疊，系統將以開始季度較新的版本優先。仍要儲存嗎？'))return;recordOperation('新增速限版本');(state.speedVersions[key]??=[]).push({id:`SV${Date.now()}`,speed,start,end,source:q('versionSource').value.trim(),checked:q('versionChecked').value,by:q('versionBy').value.trim(),note:q('versionNote').value.trim()});state.limitConfirmed[key]=true;rebuild();await save();toast('速限版本已儲存，相關季度 LOS 已重算')};

function operationSnapshot(){const code=state.activeCode;return{projects:clone(state.projects),activeCode:code,details:clone(state.details.filter(x=>x.projectCode===code)),limits:Object.fromEntries(Object.entries(state.limits).filter(([k])=>k.startsWith(`${code}|`))),limitConfirmed:Object.fromEntries(Object.entries(state.limitConfirmed).filter(([k])=>k.startsWith(`${code}|`))),aliases:Object.fromEntries(Object.entries(state.aliases).filter(([k])=>k.startsWith(`${code}|`))),roadMeta:Object.fromEntries(Object.entries(state.roadMeta).filter(([k])=>k.startsWith(`${code}|`))),speedVersions:Object.fromEntries(Object.entries(state.speedVersions).filter(([k])=>k.startsWith(`${code}|`))),losRule:clone(state.losRules[code]||null)}}
function recordOperation(name){ensureState();state.operations.unshift({id:`OP${Date.now()}${Math.random()}`,name,time:new Date().toLocaleString('zh-TW'),projectCode:state.activeCode,snapshot:operationSnapshot(),status:'可復原'});state.operations=state.operations.slice(0,10)}
async function undoOperation(id){const op=state.operations.find(x=>x.id===id);if(!op||op.status!=='可復原'||!confirm(`確定復原「${op.name}」？目前狀態會先下載備份。`))return;downloadProjectPackage(false);const s=op.snapshot,code=s.activeCode;state.details=state.details.filter(x=>x.projectCode!==code).concat(s.details);for(const bag of ['limits','limitConfirmed','aliases','roadMeta','speedVersions']){for(const k of Object.keys(state[bag]))if(k.startsWith(`${code}|`))delete state[bag][k];Object.assign(state[bag],s[bag]||{})}if(s.losRule)state.losRules[code]=s.losRule;else delete state.losRules[code];op.status='已復原';rebuild();await save();toast('操作已復原')}
function renderOperations(){if(!q('operationRows'))return;const rows=state.operations.filter(x=>!x.projectCode||x.projectCode===state.activeCode);q('operationRows').innerHTML=rows.length?rows.map(x=>`<tr><td>${safe(x.time)}</td><td>${safe(x.name)}</td><td>${safe(x.projectCode)}</td><td>${x.status==='可復原'?`<button class="outline" data-undo-operation="${safe(x.id)}">復原</button>`:safe(x.status)}</td></tr>`).join(''):'<tr><td colspan="4" class="empty">尚無可復原操作</td></tr>';document.querySelectorAll('[data-undo-operation]').forEach(b=>b.onclick=()=>undoOperation(b.dataset.undoOperation))}
function observeOperation(id){const button=q(id);if(!button)return;button.addEventListener('click',()=>{const before=operationSnapshot(),fingerprint=JSON.stringify(before);setTimeout(async()=>{if(JSON.stringify(operationSnapshot())===fingerprint)return;ensureState();state.operations.unshift({id:`OP${Date.now()}${Math.random()}`,name:button.textContent.trim(),time:new Date().toLocaleString('zh-TW'),projectCode:before.activeCode,snapshot:before,status:'可復原'});state.operations=state.operations.slice(0,10);await save()},400)},true)}
function protectHighImpactButton(id,impact){const button=q(id),original=button?.onclick;if(!button||!original)return;button.onclick=null;button.addEventListener('click',async()=>{const info=impact();if(!info.ok)return toast(info.message);if(!confirm(`${info.title}\n\n${info.detail}\n\n系統將先下載目前 Project 備份。確定繼續嗎？`))return;downloadProjectPackage(false);recordOperation(info.title);await original.call(button)})}
protectHighImpactButton('applySpeed',()=>{const inputs=[...document.querySelectorAll('[data-limit]')],changed=inputs.filter(i=>Number(i.value)!==Number(state.limits[i.dataset.limit]||50)),keys=new Set(changed.map(i=>i.dataset.limit)),affected=activeRows().filter(d=>keys.has(`${d.projectCode}|${d.road}|${d.direction}`)).length;return{ok:true,title:'套用路段速限並重算',detail:`修改 ${changed.length} 個路段方向，影響 ${affected} 筆尖峰明細。設有期間速限版本的季度仍以版本設定為準。`}});
protectHighImpactButton('applyLosRules',()=>{const rules=readLosRules();return rules?{ok:true,title:'修改服務水準門檻並重算',detail:`將重新計算目前計畫 ${activeRows().length} 筆尖峰明細、${activeSummaries().length} 筆彙總與全部相關圖表。`}:{ok:false,message:'門檻必須是 A＞B＞C＞D＞E，且介於 0～2'}});
['resetLosRules','deleteQuarter','cleanSuffix'].forEach(observeOperation);

function anomalyRule(){return{speedDrop:25,delayRise:30,losDrop:2,streak:2,...(state.anomalyRules[state.activeCode]||{})}}
function renderAnomalyRules(){const r=anomalyRule();q('ruleSpeedDrop').value=r.speedDrop;q('ruleDelayRise').value=r.delayRise;q('ruleLosDrop').value=r.losDrop;q('ruleStreak').value=r.streak}
q('saveAnomalyRules')?.addEventListener('click',async()=>{state.anomalyRules[state.activeCode]={speedDrop:Number(q('ruleSpeedDrop').value)||25,delayRise:Number(q('ruleDelayRise').value)||30,losDrop:Number(q('ruleLosDrop').value)||2,streak:Number(q('ruleStreak').value)||2};await save();inspectHealth();renderPriority();toast('異常提醒門檻已儲存')});
function priorityRows(){const r=anomalyRule(),out=[];for(const road of existingRoads())for(const day of ['平日','假日']){const seq=activeSummaries().filter(x=>x.road===road&&x.day===day).sort((a,b)=>periodKey(a.period)-periodKey(b.period));if(seq.length<1)continue;const now=seq.at(-1),prev=seq.at(-2),reasons=[];let score=6-(losRank[now.los]||6);if(prev){const speed=prev.travel?(prev.travel-now.travel)/prev.travel*100:0,delay=prev.totalDelay?(now.totalDelay-prev.totalDelay)/prev.totalDelay*100:0,los=(losRank[prev.los]||0)-(losRank[now.los]||0);if(speed>=r.speedDrop){reasons.push(`旅行速率下降 ${speed.toFixed(1)}%`);score+=2}if(delay>=r.delayRise){reasons.push(`總延滯增加 ${delay.toFixed(1)}%`);score+=2}if(los>=r.losDrop){reasons.push(`服務水準下降 ${los} 級`);score+=3}}let streak=0;for(let i=seq.length-1;i>0;i--){if((losRank[seq[i].los]||0)<(losRank[seq[i-1].los]||0)||seq[i].travel<seq[i-1].travel)streak++;else break}if(streak>=r.streak){reasons.push(`連續 ${streak} 季惡化`);score+=2}if(['E','F'].includes(now.los)){reasons.push(`目前服務水準 ${now.los}`);score+=2}if(reasons.length)out.push({road,day,period:now.period,reasons,score})}return out.sort((a,b)=>b.score-a.score)}
function renderPriority(){if(!q('priorityRows'))return;const rows=priorityRows();q('priorityRows').innerHTML=rows.length?rows.map((x,i)=>`<tr><td><b>${i+1}</b></td><td>${safe(x.road)}／${safe(x.day)}</td><td>${safe(x.period)}</td><td>${safe(x.reasons.join('；'))}</td><td>${x.score>=7?'優先查核原始資料與現地狀況':'持續觀察'}</td></tr>`).join(''):'<tr><td colspan="5" class="empty">目前沒有達到提醒門檻的路段</td></tr>'}
q('refreshPriority').onclick=renderPriority;

function deliveryRows(){const period=q('deliveryPeriod').value,road=q('deliveryRoad').value,day=q('deliveryDay').value;return activeSummaries().filter(x=>(!period||x.period===period)&&(!road||x.road===road)&&(!day||x.day===day))}
function refreshDelivery(){if(!q('deliveryPeriod'))return;const periods=ordered(activeRows().map(x=>x.period)),roads=existingRoads().sort(),oldP=q('deliveryPeriod').value,oldR=q('deliveryRoad').value;q('deliveryPeriod').innerHTML=periods.map(x=>`<option ${x===oldP?'selected':''}>${safe(x)}</option>`).join('')||'<option value="">尚無資料</option>';q('deliveryRoad').innerHTML='<option value="">全部路段</option>'+roads.map(x=>`<option ${x===oldR?'selected':''}>${safe(x)}</option>`).join('');loadDraft()}
function narrative(rows=deliveryRows()){if(!rows.length)return'目前篩選範圍沒有資料。';const p=activeProject(),period=q('deliveryPeriod').value,lines=[`${p?.code||''} ${p?.name||''} ${period} 交通服務水準分析草稿`,`本期共分析 ${new Set(rows.map(x=>x.road)).size} 個路段、${rows.length} 筆路段日別代表資料。`];for(const x of rows){const prev=activeSummaries().filter(y=>y.road===x.road&&y.day===x.day&&periodKey(y.period)<periodKey(x.period)).sort((a,b)=>periodKey(a.period)-periodKey(b.period)).at(-1);let change='無前期資料可比較';if(prev){const speed=prev.travel?(x.travel-prev.travel)/prev.travel*100:0,delay=prev.totalDelay?(x.totalDelay-prev.totalDelay)/prev.totalDelay*100:0;change=`較 ${prev.period} 旅行速率${speed>=0?'增加':'下降'} ${Math.abs(speed).toFixed(1)}%，總延滯${delay>=0?'增加':'下降'} ${Math.abs(delay).toFixed(1)}%`;}lines.push(`${x.road}（${x.day}）服務水準為 ${x.los}，代表紀錄為${x.peak}${directionName(x.road,x.direction,x.projectCode)}，旅行速率 ${fmt(x.travel,1)} km/h、總延滯 ${fmt(x.totalDelay,1)} 秒；${change}。`)}lines.push('本段文字由系統依彙總資料自動產生，正式引用前應核對原始檔、速限設定及現地情況。');return lines.join('\n')}
function draftKey(){return`${state.activeCode}|${q('deliveryPeriod')?.value||''}`}
function loadDraft(){if(q('reportDraft'))q('reportDraft').value=state.reportDrafts[draftKey()]||narrative()}
q('deliveryPeriod').onchange=loadDraft;q('deliveryRoad').onchange=loadDraft;q('deliveryDay').onchange=loadDraft;q('generateDraft').onclick=()=>q('reportDraft').value=narrative();q('saveDraft').onclick=async()=>{state.reportDrafts[draftKey()]=q('reportDraft').value;await save();toast('報告文字草稿已儲存')};
function rowsCsv(rows){if(!rows.length)return'';const fields=['period','road','day','peak','direction','travel','running','totalDelay','limit','ratio','los','sourceFile','sourceSheet','sourceHash','importBatch'];return[fields.join(','),...rows.map(x=>fields.map(k=>csvCell(x[k])).join(','))].join('\r\n')}
q('downloadQuarterPack').onclick=async()=>{const period=q('deliveryPeriod').value;if(!period)return toast('目前沒有可匯出的季度');const summaries=deliveryRows(),detail=activeRows().filter(x=>x.period===period&&(!q('deliveryRoad').value||x.road===q('deliveryRoad').value)&&(!q('deliveryDay').value||x.day===q('deliveryDay').value));inspectHealth();const zip=new JSZip(),p=activeProject(),prefix=`${p.code}_${period}`;if(q('packDetail').checked)zip.file(`${prefix}_尖峰明細.csv`,'\uFEFF'+rowsCsv(detail));if(q('packSummary').checked)zip.file(`${prefix}_尖峰彙總.csv`,'\uFEFF'+rowsCsv(summaries));if(q('packQuality').checked)zip.file(`${prefix}_資料品質檢查.json`,JSON.stringify(healthIssues.filter(x=>x.period==='全部'||x.period===period),null,2));if(q('packNarrative').checked)zip.file(`${prefix}_報告文字草稿.txt`,'\uFEFF'+q('reportDraft').value);zip.file(`${prefix}_來源追溯.json`,JSON.stringify(detail.map(x=>({id:x.id,sourceFile:x.sourceFile||x.source,sourceSheet:x.sourceSheet,sourceRefs:x.sourceRefs,sourceHash:x.sourceHash,importBatch:x.importBatch})),null,2));zip.file(`${prefix}_說明.txt`,'本成果包由交通服務水準分析系統產生。報告文字及異常提醒必須由使用者核對後使用；LOS與代表紀錄依系統既有規則計算。');downloadBlob(await zip.generateAsync({type:'blob'}),`${prefix}_季度成果包.zip`);toast('季度成果包已下載')};
q('downloadFilteredCharts').onclick=async()=>{const rows=deliveryRows(),p=activeProject(),metric=q('deliveryMetric').value;if(!rows.length)return toast('目前篩選範圍沒有資料');try{if(metric==='los')await exportLosWorkbook(rows,`${p.code}_${q('deliveryPeriod').value}_服務水準圖表.xlsx`);else await exportTravelWorkbook(rows,`${p.code}_${q('deliveryPeriod').value}_旅行速率趨勢.xlsx`);toast('篩選後可編輯 Excel 圖表已下載')}catch(e){toast(e.message||'Excel 匯出失敗')}};

const baseInspectHealth=inspectHealth;inspectHealth=function(){const base=baseInspectHealth().filter(x=>x.type!=='異常變化'),r=anomalyRule(),extra=[];for(const road of existingRoads())for(const day of ['平日','假日']){const seq=activeSummaries().filter(x=>x.road===road&&x.day===day).sort((a,b)=>periodKey(a.period)-periodKey(b.period));let streak=0;for(let i=1;i<seq.length;i++){const prev=seq[i-1],now=seq[i],losDrop=(losRank[prev.los]||0)-(losRank[now.los]||0),speedDrop=prev.travel?(prev.travel-now.travel)/prev.travel*100:0,delayRise=prev.totalDelay?(now.totalDelay-prev.totalDelay)/prev.totalDelay*100:0,worse=losDrop>0||speedDrop>0;streak=worse?streak+1:0;const reasons=[];if(losDrop>=r.losDrop)reasons.push(`服務水準 ${prev.los}→${now.los}`);if(speedDrop>=r.speedDrop)reasons.push(`旅行速率下降 ${speedDrop.toFixed(1)}%`);if(delayRise>=r.delayRise)reasons.push(`總延滯增加 ${delayRise.toFixed(1)}%`);if(streak>=r.streak)reasons.push(`連續 ${streak} 季惡化`);if(reasons.length)extra.push({type:'異常變化',period:now.period,item:`${road}／${day}`,detail:`相較 ${prev.period}：${reasons.join('；')}，請確認原始資料或現地變化。`})}}healthIssues=base.concat(extra);renderHealth();return healthIssues};

const baseRenderAll=renderAll;renderAll=function(){ensureState();baseRenderAll();renderTrace();renderSpeedVersions();renderAnomalyRules();renderPriority();refreshDelivery();renderOperations()};
renderAll();
})();
